name: huezumi

services:
  huezumi:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - huezumi-data:/app/.data
    restart: unless-stopped

volumes:
  huezumi-data:
