import type { GenerationMode, MediaType, ModelSpec, ProviderCapability, Resolution } from '#shared/types/generation'

/**
 * 供应商能力目录 —— 全平台唯一的"谁支持什么"声明源。
 *
 * 扩展新供应商的完整步骤：
 * 1. 在 shared/types/generation.ts 的 ProviderId 联合类型中加上新 id；
 * 2. 新建 adapters/<id>.ts 实现 VideoProvider（submit + getTask）；
 * 3. 在本文件追加一份 ProviderCapability 声明；
 * 4. 在 ./index.ts 的工厂函数中按 env 凭据注册。
 * 前端（创作台 / 首页能力矩阵）全部由 /api/providers 驱动，零改动。
 */

/** 首帧 / 尾帧素材的通用限制 */
const frameLimits = {
  accept: 'image/*',
  extensions: ['jpg', 'jpeg', 'png', 'webp'],
  maxBytes: 20 * 1024 * 1024,
  max: 1,
}

/** 参考类素材的通用限制，供模型级 mediaLimits 覆盖复用（仅替换数量等差异项） */
const imageReferenceLimit = { accept: 'image/*', extensions: ['jpg', 'jpeg', 'png', 'webp'], maxBytes: 20 * 1024 * 1024 }
const videoReferenceLimit = { accept: 'video/*', extensions: ['mp4', 'mov'], maxBytes: 100 * 1024 * 1024, duration: { min: 1, max: 30 } }
const audioReferenceLimit = { accept: 'audio/*', extensions: ['mp3', 'wav'], maxBytes: 15 * 1024 * 1024, duration: { min: 2, max: 30 } }

const rollDekResolutions: Extract<Resolution, '480P' | '720P' | '1080P'>[] = ['480P', '720P', '1080P']
const rollDekVideoModes: GenerationMode[] = ['text', 'frames', 'reference']
const rollDekVideoMedia: MediaType[] = ['first_frame', 'last_frame', 'reference_image', 'reference_video', 'reference_audio']
const rollDekImageModes: GenerationMode[] = ['frames', 'reference']
const rollDekImageMedia: MediaType[] = ['first_frame', 'last_frame', 'reference_image', 'reference_audio']

/** Runway URL 输入限制；本地上传先转为公网 URL，因此按 URL 上限约束文件选择。 */
const runwayImageLimit = {
  accept: 'image/*',
  extensions: ['jpg', 'jpeg', 'png', 'webp'],
  maxBytes: 16 * 1024 * 1024,
}
const runwayVideoLimit = {
  accept: 'video/*',
  extensions: ['mp4', 'mov', 'webm', 'mkv'],
  maxBytes: 32 * 1024 * 1024,
  duration: { min: 1, max: 30 },
  totalDuration: 30,
}
const runwayAudioLimit = {
  accept: 'audio/*',
  extensions: ['mp3', 'wav', 'flac', 'm4a', 'aac'],
  maxBytes: 32 * 1024 * 1024,
  duration: { min: 2, max: 30 },
  totalDuration: 30,
}
const runwayFrameLimit = { ...runwayImageLimit, max: 1 }
const runwayMultimodalMedia: MediaType[] = ['first_frame', 'last_frame', 'reference_image', 'reference_video', 'reference_audio']

const runwayModels: ModelSpec[] = [
  {
    id: 'gen4.5',
    name: 'Gen-4.5',
    description: '文生 / 首帧图生 · 2–10 秒',
    badge: '旗舰',
    capabilities: {
      modes: ['text', 'frames'],
      media: ['first_frame'],
      resolutions: ['720P'],
      ratios: ['16:9', '9:16', '4:3', '1:1', '3:4', '21:9'],
      duration: { min: 2, max: 10, smart: false, videoAware: false },
      supportsAudio: false,
      supportsNegativePrompt: false,
      supportsSeed: true,
      supportsPromptExtend: false,
      supportsWatermark: false,
      supportsMediaOnly: false,
      mediaLimits: { first_frame: runwayFrameLimit },
      notes: '官方 image_to_video 端点同时支持文本生成；无首帧时省略 promptImage。官方没有独立 resolution 字段，实际尺寸由 ratio 决定。',
    },
  },
  {
    id: 'wan3',
    name: 'WAN 3.0',
    description: '文本 / 图片 / 视频 / 音频参考 · 2–30 秒',
    badge: '多模态',
    capabilities: {
      modes: ['text', 'frames', 'reference'],
      media: runwayMultimodalMedia,
      resolutions: ['480P', '720P', '1080P'],
      ratios: ['adaptive', '16:9', '4:3', '1:1', '3:4', '9:16'],
      duration: { min: 2, max: 30, smart: false, videoAware: false },
      supportsAudio: true,
      supportsNegativePrompt: false,
      supportsSeed: false,
      supportsPromptExtend: false,
      supportsWatermark: false,
      supportsMediaOnly: false,
      mediaLimits: {
        first_frame: runwayFrameLimit,
        last_frame: runwayFrameLimit,
        reference_image: { ...runwayImageLimit, max: 10 },
        reference_video: { ...runwayVideoLimit, max: 5, totalDuration: 15 },
        reference_audio: { ...runwayAudioLimit, max: 5, totalDuration: 15 },
      },
      notes: '无视频输入时使用 text_to_video 或 image_to_video；参考视频和参考音频分别映射到 referenceVideos、referenceAudio。',
    },
  },
  {
    id: 'seedance2_5',
    name: 'Seedance 2.5',
    description: '文本 / 图片 / 视频 / 音频参考 · 4–30 秒',
    badge: '多模态',
    capabilities: {
      modes: ['text', 'frames', 'reference'],
      media: runwayMultimodalMedia,
      resolutions: ['480P', '720P', '1080P'],
      ratios: ['21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
      duration: { min: 4, max: 30, smart: true, videoAware: false },
      supportsAudio: true,
      supportsNegativePrompt: false,
      supportsSeed: true,
      supportsPromptExtend: false,
      supportsWatermark: false,
      supportsMediaOnly: false,
      mediaLimits: {
        first_frame: runwayFrameLimit,
        last_frame: runwayFrameLimit,
        reference_image: { ...runwayImageLimit, max: 30 },
        reference_video: { ...runwayVideoLimit, max: 9 },
        reference_audio: { ...runwayAudioLimit, max: 10 },
      },
      notes: '图片请求使用 promptImage，视频请求使用 video_to_video；视频模式固定为官方 reference，不把平台 reference 模式冒充 extend/edit。',
    },
  },
  {
    id: 'seedance2',
    name: 'Seedance 2.0',
    description: '文本 / 图片 / 视频 / 音频参考 · 4–15 秒',
    badge: '多模态',
    capabilities: {
      modes: ['text', 'frames', 'reference'],
      media: runwayMultimodalMedia,
      resolutions: ['480P', '720P', '1080P', '4K'],
      ratios: ['21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
      duration: { min: 4, max: 15, smart: true, videoAware: false },
      supportsAudio: true,
      supportsNegativePrompt: false,
      supportsSeed: true,
      supportsPromptExtend: false,
      supportsWatermark: false,
      supportsMediaOnly: false,
      mediaLimits: {
        first_frame: runwayFrameLimit,
        last_frame: runwayFrameLimit,
        reference_image: { ...runwayImageLimit, max: 9 },
        reference_video: { ...runwayVideoLimit, max: 3, totalDuration: 15 },
        reference_audio: { ...runwayAudioLimit, max: 3, totalDuration: 15 },
      },
      notes: '支持 480P、720P、1080P 和 4K 的官方像素 ratio；带视频参考时切换到 video_to_video。',
    },
  },
  {
    id: 'seedance2_fast',
    name: 'Seedance 2.0 Fast',
    description: '高速多模态生成 · 4–15 秒',
    badge: '高速 / 多模态',
    capabilities: {
      modes: ['text', 'frames', 'reference'],
      media: runwayMultimodalMedia,
      resolutions: ['480P', '720P'],
      ratios: ['21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
      duration: { min: 4, max: 15, smart: true, videoAware: false },
      supportsAudio: true,
      supportsNegativePrompt: false,
      supportsSeed: true,
      supportsPromptExtend: false,
      supportsWatermark: false,
      supportsMediaOnly: false,
      mediaLimits: {
        first_frame: runwayFrameLimit,
        last_frame: runwayFrameLimit,
        reference_image: { ...runwayImageLimit, max: 9 },
        reference_video: { ...runwayVideoLimit, max: 3, totalDuration: 15 },
        reference_audio: { ...runwayAudioLimit, max: 3, totalDuration: 15 },
      },
      notes: '官方仅开放 480P / 720P；请求结构与 Seedance 2.0 一致。',
    },
  },
  {
    id: 'seedance2_mini',
    name: 'Seedance 2.0 Mini',
    description: '轻量多模态生成 · 4–15 秒',
    badge: '轻量 / 多模态',
    capabilities: {
      modes: ['text', 'frames', 'reference'],
      media: runwayMultimodalMedia,
      resolutions: ['480P', '720P'],
      ratios: ['21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
      duration: { min: 4, max: 15, smart: true, videoAware: false },
      supportsAudio: true,
      supportsNegativePrompt: false,
      supportsSeed: true,
      supportsPromptExtend: false,
      supportsWatermark: false,
      supportsMediaOnly: false,
      mediaLimits: {
        first_frame: runwayFrameLimit,
        last_frame: runwayFrameLimit,
        reference_image: { ...runwayImageLimit, max: 9 },
        reference_video: { ...runwayVideoLimit, max: 3, totalDuration: 15 },
        reference_audio: { ...runwayAudioLimit, max: 3, totalDuration: 15 },
      },
      notes: '官方仅开放 480P / 720P；请求结构与 Seedance 2.0 一致。',
    },
  },
  {
    id: 'hailuo3',
    name: 'Hailuo 3',
    description: '文本 / 图片 / 视频 / 音频参考 · 5–15 秒',
    badge: '多模态',
    capabilities: {
      modes: ['text', 'frames', 'reference'],
      media: runwayMultimodalMedia,
      resolutions: ['768P', '2K'],
      ratios: ['21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
      duration: { min: 5, max: 15, smart: false, videoAware: false },
      supportsAudio: false,
      supportsNegativePrompt: false,
      supportsSeed: false,
      supportsPromptExtend: false,
      supportsWatermark: false,
      supportsMediaOnly: false,
      mediaLimits: {
        first_frame: runwayFrameLimit,
        last_frame: runwayFrameLimit,
        reference_image: { ...runwayImageLimit, max: 9 },
        reference_video: { ...runwayVideoLimit, max: 2, totalDuration: 15 },
        reference_audio: { ...runwayAudioLimit, max: 3, totalDuration: 15 },
      },
      notes: '图片和视频分别走 image_to_video、video_to_video；官方将 768P / 2K 作为独立 resolution 字段。',
    },
  },
  {
    id: 'gemini_omni_flash',
    name: 'Gemini Omni Flash',
    description: '文本 / 首帧 / 视频编辑 · 3–10 秒',
    badge: '视频编辑',
    capabilities: {
      modes: ['text', 'frames', 'reference'],
      media: ['first_frame', 'reference_image', 'reference_video'],
      resolutions: ['720P'],
      ratios: ['16:9', '9:16'],
      duration: { min: 3, max: 10, smart: false, videoAware: false },
      supportsAudio: false,
      supportsNegativePrompt: false,
      supportsSeed: false,
      supportsPromptExtend: false,
      supportsWatermark: false,
      supportsMediaOnly: false,
      mediaLimits: {
        first_frame: runwayFrameLimit,
        // Gemini 的 image_to_video 只接受一个首帧；视频编辑模式的额外参考图
        // 能力没有在平台契约中按 endpoint 区分，因此统一收敛为一个，避免 UI
        // 允许多个图片后被 image_to_video 拒绝。
        reference_image: { ...runwayImageLimit, max: 1 },
        reference_video: { ...runwayVideoLimit, max: 1, totalDuration: 10 },
      },
      notes: '单视频输入走 video_to_video，输出 720P 且时长跟随输入（最多 10 秒）；视频编辑可额外带参考图。',
    },
  },
]

/** RollDek 模型名自带清晰度后缀；每个模型只开放与后缀一致的 platform resolution。 */
const rollDekModels: ModelSpec[] = [
  ...rollDekResolutions.map(resolution => ({
    id: `wan3.0-video-${resolution.toLowerCase()}`,
    name: `WAN 3.0 标准 · ${resolution}`,
    description: '文生 / 首尾帧 / 多模态参考',
    badge: '标准',
    capabilities: {
      modes: rollDekVideoModes,
      media: rollDekVideoMedia,
      resolutions: [resolution],
      duration: { min: 2, max: 30, smart: false, videoAware: false },
      notes: `模型后缀固定输出 ${resolution}；参考视频时长计入计费秒数。`,
    },
  })),
  ...rollDekResolutions.map(resolution => ({
    id: `wan3.0-video-prime-${resolution.toLowerCase()}`,
    name: `WAN 3.0 Prime · ${resolution}`,
    description: '高速版 · 文生 / 首尾帧 / 多模态参考',
    badge: '高速',
    capabilities: {
      modes: rollDekVideoModes,
      media: rollDekVideoMedia,
      resolutions: [resolution],
      duration: { min: 2, max: 30, smart: false, videoAware: false },
      notes: `模型后缀固定输出 ${resolution}；参考视频时长计入计费秒数。`,
    },
  })),
  ...rollDekResolutions.map(resolution => ({
    id: `wan3.0-image-${resolution.toLowerCase()}`,
    name: `WAN 3.0 Image · ${resolution}`,
    description: '图生视频专用 · 图片 / 音频参考',
    badge: '图生',
    capabilities: {
      modes: rollDekImageModes,
      media: rollDekImageMedia,
      resolutions: [resolution],
      duration: { min: 2, max: 30, smart: false, videoAware: false },
      notes: `模型后缀固定输出 ${resolution}；不支持参考视频，仅按输出时长计费。`,
    },
  })),
  ...rollDekResolutions.map(resolution => ({
    id: `wan3.0-image-prime-${resolution.toLowerCase()}`,
    name: `WAN 3.0 Image Prime · ${resolution}`,
    description: '图生视频高速版 · 图片 / 音频参考',
    badge: '图生高速',
    capabilities: {
      modes: rollDekImageModes,
      media: rollDekImageMedia,
      resolutions: [resolution],
      duration: { min: 2, max: 30, smart: false, videoAware: false },
      notes: `模型后缀固定输出 ${resolution}；不支持参考视频，仅按输出时长计费。`,
    },
  })),
]

export const providerCapabilities: ProviderCapability[] = [
  {
    id: 'dashscope',
    name: '阿里云百炼',
    vendor: 'Alibaba Cloud',
    enabled: true,
    models: [
      {
        id: 'wan3.0-video-prime',
        name: 'Wan 3.0 Prime',
        description: '高速版 · 能力对齐标准版 · 原生有声',
        badge: '高速',
        capabilities: {
          resolutions: ['480P', '720P', '1080P'],
          notes: 'All-in-One 文生、首尾帧与多模态参考；480P/720P/1080P；2–30 秒或智能时长；支持音频开关。',
        },
      },
      {
        id: 'wan3.0-video',
        name: 'Wan 3.0',
        description: '标准版 · All-in-One 多模态参考 · 原生有声',
        capabilities: {
          resolutions: ['480P', '720P', '1080P'],
          notes: 'All-in-One 文生、首尾帧与多模态参考；480P/720P/1080P；2–30 秒或智能时长；支持音频开关。',
        },
      },
      {
        id: 'happyhorse-1.1-t2v',
        name: 'HappyHorse 1.1 T2V',
        description: '文生视频 · 3–15 秒',
        capabilities: {
          modes: ['text'],
          media: [],
          resolutions: ['480P', '720P', '1080P'],
          ratios: ['16:9', '9:16', '1:1', '4:3', '3:4', '21:9'],
          duration: { min: 3, max: 15, smart: false, videoAware: false },
          supportsNegativePrompt: false,
          supportsSeed: true,
          supportsPromptExtend: false,
          supportsAudio: false,
          notes: '官方未声明音频生成参数；水印默认开启；另支持 4:5/5:4/9:21 画幅，平台未开放。',
        },
      },
      {
        id: 'happyhorse-1.1-i2v',
        name: 'HappyHorse 1.1 I2V',
        description: '首帧图生视频 · 画幅跟随首帧',
        capabilities: {
          modes: ['frames'],
          media: ['first_frame'],
          resolutions: ['480P', '720P', '1080P'],
          ratios: [],
          duration: { min: 3, max: 15, smart: false, videoAware: false },
          supportsNegativePrompt: false,
          supportsSeed: true,
          supportsPromptExtend: false,
          supportsAudio: false,
          notes: '有且仅有一张首帧；输出画幅跟随首帧，不支持 ratio；官方未声明音频生成参数，水印默认开启。',
        },
      },
      {
        id: 'happyhorse-1.1-r2v',
        name: 'HappyHorse 1.1 R2V',
        description: '参考生视频 · 最多 9 张参考图',
        capabilities: {
          modes: ['reference'],
          media: ['reference_image'],
          resolutions: ['480P', '720P', '1080P'],
          ratios: ['16:9', '9:16', '1:1', '4:3', '3:4', '21:9'],
          duration: { min: 3, max: 15, smart: false, videoAware: false },
          supportsNegativePrompt: false,
          supportsSeed: true,
          supportsPromptExtend: false,
          supportsAudio: false,
          mediaLimits: {
            reference_image: { ...imageReferenceLimit, max: 9 },
          },
          notes: '官方以 [Image N] 指代参考图，平台透传提示词，建议在提示词中描述各图用途；官方未声明音频生成参数，水印默认开启。',
        },
      },
      {
        id: 'wan2.7-t2v',
        name: 'Wan 2.7 T2V',
        description: '文生视频 · 多镜头叙事 · 原生音频',
        badge: '有声',
        capabilities: {
          modes: ['text', 'reference'],
          media: ['reference_audio'],
          resolutions: ['720P', '1080P'],
          ratios: ['16:9', '9:16', '1:1', '4:3', '3:4'],
          duration: { min: 2, max: 15, smart: false, videoAware: false },
          supportsSeed: true,
          mediaLimits: {
            reference_audio: { ...audioReferenceLimit, max: 1, duration: { min: 2, max: 30 } },
          },
          notes: '音频直出；参考音频映射为 audio_url 驱动口型与卡点（2–30 秒，≤15MB），未传时自动配乐。',
        },
      },
      {
        id: 'wan2.7-i2v',
        name: 'Wan 2.7 I2V',
        description: '首帧/首尾帧 · 音频驱动 · 视频续写',
        capabilities: {
          modes: ['frames', 'reference'],
          media: ['first_frame', 'last_frame', 'reference_audio', 'reference_video'],
          resolutions: ['720P', '1080P'],
          ratios: [],
          duration: { min: 2, max: 15, smart: false, videoAware: false },
          supportsSeed: true,
          mediaLimits: {
            reference_audio: { ...audioReferenceLimit, max: 1 },
            reference_video: { ...videoReferenceLimit, max: 1 },
          },
          notes: '输出画幅跟随输入素材，不支持 ratio；驱动音频需与首帧搭配；参考视频按视频续写（first_clip）处理，输出总时长 = duration。',
        },
      },
      {
        id: 'wan2.7-r2v-2026-06-12',
        name: 'Wan 2.7 R2V',
        description: '参考生视频 · 图/视频混合 ≤5 · 音色随参考',
        badge: '快照',
        capabilities: {
          modes: ['reference'],
          media: ['first_frame', 'reference_image', 'reference_video'],
          resolutions: ['720P', '1080P'],
          ratios: ['16:9', '9:16', '1:1', '4:3', '3:4'],
          duration: { min: 2, max: 10, smart: false, videoAware: false },
          supportsSeed: true,
          mediaLimits: {
            reference_image: { ...imageReferenceLimit, max: 5 },
            reference_video: { ...videoReferenceLimit, max: 5 },
          },
          mediaCombinationLimits: [{
            types: ['reference_image', 'reference_video'],
            max: 5,
            message: '参考图与参考视频合计最多 5 个',
          }],
          notes: '参考图与参考视频至少传入 1 个，合计最多 5 个；传首帧时画幅由首帧决定；音色随参考视频自动继承，逐素材音色参考暂未暴露。',
        },
      },
      {
        id: 'MiniMax/MiniMax-H3',
        name: 'MiniMax H3',
        description: '全模态参考 · 最高 2K · 原生立体声',
        badge: '2K',
        capabilities: {
          modes: ['text', 'frames', 'reference'],
          media: ['first_frame', 'last_frame', 'reference_image', 'reference_video', 'reference_audio'],
          resolutions: ['768P', '2K'],
          ratios: ['16:9', '9:16', '1:1', '4:3', '21:9'],
          duration: { min: 4, max: 15, smart: false, videoAware: false },
          supportsNegativePrompt: false,
          supportsSeed: false,
          supportsPromptExtend: false,
          mediaLimits: {
            reference_image: { ...imageReferenceLimit, max: 9 },
            reference_video: { ...videoReferenceLimit, max: 3, totalDuration: 15 },
            reference_audio: { ...audioReferenceLimit, max: 3, totalDuration: 15 },
          },
          notes: '经百炼统一接口调用 MiniMax-H3（推理服务商稀宇科技）；原生立体声直出、无声音开关；最多 9 张参考图、3 个参考视频、3 个参考音频，音视频总时长 ≤15 秒；官方未声明 seed/改写/反向提示词，故不下发；画幅必须显式选择，不支持自适应。',
        },
      },
      {
        id: 'kling/kling-v3-turbo-video-generation',
        name: 'Kling V3 Turbo（百炼）',
        description: '文生 / 首帧 · 固定音画同出 · 更快更省',
        badge: '有声',
        capabilities: {
          modes: ['text', 'frames'],
          media: ['first_frame'],
          resolutions: ['720P', '1080P'],
          ratios: ['16:9', '9:16', '1:1'],
          duration: { min: 3, max: 15, smart: false, videoAware: false },
          supportsNegativePrompt: false,
          supportsSeed: false,
          supportsPromptExtend: false,
          mediaLimits: {
            first_frame: { accept: 'image/*', extensions: ['jpg', 'jpeg', 'png'], maxBytes: 10 * 1024 * 1024, max: 1 },
          },
          notes: '仅北京地域；固定生成有声视频（audio 开关不生效）；不支持尾帧、反向提示词与 4K；素材 10MB / [300,8000]px。',
        },
      },
      {
        id: 'kling/kling-v3-video-generation',
        name: 'Kling V3（百炼）',
        description: '文生 / 首尾帧 · 最高 4K',
        badge: '4K',
        capabilities: {
          modes: ['text', 'frames'],
          media: ['first_frame', 'last_frame'],
          resolutions: ['720P', '1080P', '4K'],
          ratios: ['16:9', '9:16', '1:1'],
          duration: { min: 3, max: 15, smart: false, videoAware: false },
          supportsNegativePrompt: true,
          supportsSeed: false,
          supportsPromptExtend: false,
          mediaLimits: {
            first_frame: { accept: 'image/*', extensions: ['jpg', 'jpeg', 'png'], maxBytes: 10 * 1024 * 1024, max: 1 },
            last_frame: { accept: 'image/*', extensions: ['jpg', 'jpeg', 'png'], maxBytes: 10 * 1024 * 1024, max: 1 },
          },
          notes: '仅北京地域；支持 4K 模式与反向提示词；音频默认关闭；素材 10MB / [300,8000]px。',
        },
      },
      {
        id: 'kling/kling-v3-omni-video-generation',
        name: 'Kling V3 Omni（百炼）',
        description: '文生 / 首尾帧 / 参考生 · 最高 4K',
        badge: '4K',
        capabilities: {
          modes: ['text', 'frames', 'reference'],
          media: ['first_frame', 'last_frame', 'reference_image', 'reference_video'],
          resolutions: ['720P', '1080P', '4K'],
          ratios: ['16:9', '9:16', '1:1'],
          duration: { min: 3, max: 15, smart: false, videoAware: false },
          supportsNegativePrompt: true,
          supportsSeed: false,
          supportsPromptExtend: false,
          mediaLimits: {
            first_frame: { accept: 'image/*', extensions: ['jpg', 'jpeg', 'png'], maxBytes: 10 * 1024 * 1024, max: 1 },
            last_frame: { accept: 'image/*', extensions: ['jpg', 'jpeg', 'png'], maxBytes: 10 * 1024 * 1024, max: 1 },
            reference_image: { ...imageReferenceLimit, max: 7 },
            reference_video: { accept: 'video/*', extensions: ['mp4', 'mov'], maxBytes: 200 * 1024 * 1024, max: 1, duration: { min: 3, max: 15.5 } },
          },
          mediaCombinationLimits: [{
            types: ['reference_image'],
            whenTypes: ['reference_video'],
            max: 4,
            message: '带参考视频时，参考图最多 4 张',
          }],
          notes: '仅北京地域；仅参考图时最多 7 张；带参考视频时视频 1 个且参考图最多 4 张；在提示词中用 <<<image_N>>> / <<<video_N>>> 引用。视频编辑（base）、主体列表与多镜头自定义暂未暴露。',
        },
      },
    ],
    modes: ['text', 'frames', 'reference'],
    media: ['first_frame', 'last_frame', 'reference_image', 'reference_video', 'reference_audio', 'file', 'link'],
    mediaLimits: {
      first_frame: frameLimits,
      last_frame: frameLimits,
      reference_image: { ...imageReferenceLimit, max: 10 },
      reference_video: { ...videoReferenceLimit, max: 5, duration: { min: 1, max: 15 } },
      reference_audio: { ...audioReferenceLimit, max: 5, duration: { min: 1, max: 15 } },
    },
    resolutions: ['480P', '768P', '720P', '1080P', '2K', '4K'],
    ratios: ['adaptive', '16:9', '4:3', '1:1', '3:4', '9:16'],
    duration: { min: 2, max: 30, smart: true, videoAware: true },
    supportsAudio: true,
    supportsNegativePrompt: true,
    supportsSeed: true,
    supportsWatermark: true,
    supportsPromptExtend: true,
    supportsMediaOnly: true,
    notes: '百炼官方视频生成目录包含 HappyHorse、万相、人像驱动、PixVerse、可灵和 Vidu。当前平台已适配其中的 HappyHorse、万相、可灵，并额外接入百炼模型市场的 MiniMax H3；PixVerse、Vidu 和人像驱动尚未映射到平台契约。wan3.0 参考素材上限为 10 图 / 5 视频 / 5 音频，视频和音频总时长均不超过 15 秒。',
    docsUrl: 'https://help.aliyun.com/zh/model-studio/video-generation-api/',
  },
  {
    id: 'minimax',
    name: 'MiniMax 海螺',
    vendor: 'MiniMax',
    enabled: true,
    models: [
      {
        id: 'MiniMax-Hailuo-2.3',
        name: 'Hailuo 2.3',
        description: '文生 / 首帧图生 · 15 种运镜指令',
        badge: '推荐',
        capabilities: {
          modes: ['text', 'frames'],
          media: ['first_frame'],
          durationByResolution: { '768P': [6, 10], '1080P': [6] },
          notes: '支持文生和首帧图生；1080P 仅支持 6 秒。',
        },
      },
      {
        id: 'MiniMax-Hailuo-2.3-Fast',
        name: 'Hailuo 2.3 Fast',
        description: '首帧图生 · 2.3 快速版',
        badge: '快速',
        capabilities: {
          modes: ['frames'],
          media: ['first_frame'],
          durationByResolution: { '768P': [6, 10], '1080P': [6] },
          notes: '仅支持首帧图生；768P 支持 6/10 秒，1080P 仅支持 6 秒。',
        },
      },
      {
        id: 'MiniMax-Hailuo-02',
        name: 'Hailuo 02',
        description: '文生 / 首帧图生 / 严格首尾帧',
        capabilities: {
          modes: ['text', 'frames'],
          media: ['first_frame', 'last_frame'],
          durationByResolution: { '768P': [6, 10], '1080P': [6] },
          notes: '支持严格首尾帧；1080P 仅支持 6 秒；官方另提供 512P 档（6/10 秒），平台未开放。',
        },
      },
    ],
    modes: ['text', 'frames'],
    media: ['first_frame', 'last_frame'],
    mediaLimits: {
      first_frame: frameLimits,
      last_frame: frameLimits,
    },
    resolutions: ['768P', '1080P'],
    ratios: [],
    duration: { min: 6, max: 10, smart: false, videoAware: false, steps: [6, 10] },
    supportsAudio: false,
    supportsNegativePrompt: false,
    supportsSeed: false,
    supportsWatermark: true,
    supportsPromptExtend: true,
    supportsMediaOnly: true,
    notes: '画幅由模型或首帧决定；768P 支持 6/10 秒，1080P 仅支持 6 秒。当前直连 v1 接入 Hailuo 2.3 / 2.3 Fast / 02；旧版 T2V-01、I2V-01 系列未纳入。MiniMax-H3 已通过百炼接入，MiniMax 自有平台的 H3 / H3 Max 使用 v2 content 协议，尚未适配。',
    docsUrl: 'https://platform.minimaxi.com/docs/api-reference/video-generation-t2v',
  },
  {
    id: 'kling',
    name: '可灵 Kling',
    vendor: '快手',
    enabled: true,
    models: [
      {
        id: 'kling-v2-6',
        name: 'Kling V2.6',
        description: '文生 / 图生 · 原生音画同出',
        badge: '有声',
        capabilities: {
          modes: ['text', 'frames'],
          media: ['first_frame', 'last_frame'],
          resolutions: ['1080P'],
          supportsAudio: true,
          notes: '官方 V2.6 支持 720P/1080P 与 5/10 秒；生成有声视频时仅支持 1080P，因此平台按 1080P 提交。',
        },
      },
      {
        id: 'kling-v2-5-turbo',
        name: 'Kling V2.5 Turbo',
        description: '文生 / 图生 · 高性价比',
        capabilities: {
          modes: ['text', 'frames'],
          media: ['first_frame', 'last_frame'],
          resolutions: ['720P', '1080P'],
          supportsAudio: false,
          notes: '支持 720P/1080P 与 5/10 秒；尾帧必须搭配首帧，且仅 1080P 专家模式支持。',
        },
      },
    ],
    modes: ['text', 'frames'],
    media: ['first_frame', 'last_frame'],
    mediaLimits: {
      first_frame: frameLimits,
      last_frame: { ...frameLimits, hint: '需搭配首帧，且仅专家模式支持' },
    },
    resolutions: ['720P', '1080P'],
    ratios: ['16:9', '9:16', '1:1'],
    duration: { min: 5, max: 10, smart: false, videoAware: false, steps: [5, 10] },
    supportsAudio: true,
    supportsNegativePrompt: true,
    supportsSeed: false,
    supportsWatermark: true,
    supportsPromptExtend: false,
    supportsMediaOnly: false,
    notes: '平台当前接入 V2.6 与 V2.5 Turbo；声音仅 V2.6 支持，且官方要求有声输出必须为 1080P。V2.1 / V2.1 Master 等早期模型官方将于 2026-09-15 下线；Kling 3.0 系列已通过百炼统一接口接入（见阿里云百炼供应商下的 Kling V3 模型），可灵自有平台（JWT 鉴权）的 3.0 端点暂未适配。',
    docsUrl: 'https://app.klingai.com/cn/dev/document-api/apiReference/commonInfo',
  },
  {
    id: 'seedance',
    name: 'Seedance 即梦',
    vendor: '字节跳动 · 火山方舟',
    enabled: true,
    models: [
      {
        id: 'doubao-seedance-1-5-pro-251215',
        name: 'Seedance 1.5 Pro',
        description: '文生 / 图生 · 同步音频 · 智能时长',
        badge: '即将下线',
        capabilities: {
          duration: { min: 4, max: 12, smart: true, videoAware: false },
          supportsAudio: true,
          notes: '支持 4–12 秒或智能时长，可生成同步音频；官方模型列表已标记即将下线。',
        },
      },
      {
        id: 'doubao-seedance-1-0-pro-fast-251015',
        name: 'Seedance 1.0 Pro Fast',
        description: '文生 / 图生 · 快速出片',
        capabilities: {
          duration: { min: 2, max: 12, smart: false, videoAware: false },
          media: ['first_frame'],
          supportsAudio: false,
          notes: '支持 2–12 秒；官方该模型不支持尾帧、智能时长、自适应画幅与同步音频。',
        },
      },
      {
        id: 'doubao-seedance-1-0-pro-250528',
        name: 'Seedance 1.0 Pro',
        description: '文生 / 图生 · 标准 Pro',
        capabilities: {
          duration: { min: 2, max: 12, smart: false, videoAware: false },
          supportsAudio: false,
          notes: '支持 2–12 秒，不支持智能时长和同步音频。',
        },
      },
      {
        id: 'doubao-seedance-2-0-260128',
        name: 'Seedance 2.0',
        description: '全模态参考生成 · 最高 4K',
        badge: '4K',
        capabilities: {
          modes: ['text', 'frames', 'reference'],
          media: ['first_frame', 'last_frame', 'reference_image', 'reference_video', 'reference_audio'],
          resolutions: ['480P', '720P', '1080P', '4K'],
          ratios: ['adaptive', '16:9', '4:3', '1:1', '3:4', '9:16', '21:9'],
          duration: { min: 4, max: 15, smart: false, videoAware: false },
          supportsAudio: true,
          mediaLimits: {
            reference_image: { ...imageReferenceLimit, max: 9 },
            reference_video: { ...videoReferenceLimit, max: 3, totalDuration: 15 },
            reference_audio: { ...audioReferenceLimit, max: 3, totalDuration: 15 },
          },
          notes: '4–15 秒；支持 480P/720P/1080P 与 4K（10bit）；参考图最多 9 张、参考视频/音频各 3 个且各自总时长不超过 15 秒；参考音频不可单独输入。上游另支持编辑与延长，平台尚未暴露对应任务结构。',
        },
      },
      {
        id: 'doubao-seedance-2-0-fast-260128',
        name: 'Seedance 2.0 Fast',
        description: '全模态参考 · 快速版 · 最高 720P',
        badge: '快速',
        capabilities: {
          modes: ['text', 'frames', 'reference'],
          media: ['first_frame', 'last_frame', 'reference_image', 'reference_video', 'reference_audio'],
          resolutions: ['480P', '720P'],
          ratios: ['adaptive', '16:9', '4:3', '1:1', '3:4', '9:16', '21:9'],
          duration: { min: 4, max: 15, smart: false, videoAware: false },
          supportsAudio: true,
          mediaLimits: {
            reference_image: { ...imageReferenceLimit, max: 9 },
            reference_video: { ...videoReferenceLimit, max: 3, totalDuration: 15 },
            reference_audio: { ...audioReferenceLimit, max: 3, totalDuration: 15 },
          },
          notes: '4–15 秒；仅 480P/720P；全模态参考能力与 2.0 标准版一致，侧重速度与成本。上游编辑与延长能力尚未在平台暴露。',
        },
      },
      {
        id: 'doubao-seedance-2-0-mini-260615',
        name: 'Seedance 2.0 Mini',
        description: '全模态参考 · 低成本版 · 最高 720P',
        badge: '轻量',
        capabilities: {
          modes: ['text', 'frames', 'reference'],
          media: ['first_frame', 'last_frame', 'reference_image', 'reference_video', 'reference_audio'],
          resolutions: ['480P', '720P'],
          ratios: ['adaptive', '16:9', '4:3', '1:1', '3:4', '9:16', '21:9'],
          duration: { min: 4, max: 15, smart: false, videoAware: false },
          supportsAudio: true,
          mediaLimits: {
            reference_image: { ...imageReferenceLimit, max: 9 },
            reference_video: { ...videoReferenceLimit, max: 3, totalDuration: 15 },
            reference_audio: { ...audioReferenceLimit, max: 3, totalDuration: 15 },
          },
          notes: '4–15 秒；仅 480P/720P；全模态参考能力与 2.0 标准版一致，侧重最低成本。上游编辑与延长能力尚未在平台暴露。',
        },
      },
      {
        id: 'doubao-seedance-2-5-260628',
        name: 'Seedance 2.5',
        description: '全模态参考生成 · 最长 30 秒',
        badge: '有声',
        capabilities: {
          modes: ['text', 'frames', 'reference'],
          media: ['first_frame', 'last_frame', 'reference_image', 'reference_video', 'reference_audio'],
          resolutions: ['480P', '720P', '1080P'],
          ratios: ['adaptive', '16:9', '4:3', '1:1', '3:4', '9:16', '21:9'],
          duration: { min: 4, max: 30, smart: false, videoAware: false },
          supportsAudio: true,
          mediaLimits: {
            reference_image: { ...imageReferenceLimit, max: 30 },
            reference_video: { ...videoReferenceLimit, max: 10, totalDuration: 30 },
            reference_audio: { ...audioReferenceLimit, max: 10, totalDuration: 30 },
          },
          notes: '4–30 秒；支持 480P/720P/1080P，不支持 4K；参考图最多 30 张、参考视频/音频各 10 个且各自总时长不超过 30 秒；支持仅音频参考。上游另支持编辑与延长，平台尚未暴露对应任务结构。',
        },
      },
    ],
    modes: ['text', 'frames'],
    media: ['first_frame', 'last_frame'],
    mediaLimits: {
      first_frame: frameLimits,
      last_frame: frameLimits,
    },
    resolutions: ['480P', '720P', '1080P'],
    ratios: ['16:9', '4:3', '1:1', '3:4', '9:16', '21:9'],
    duration: { min: 2, max: 12, smart: true, videoAware: false },
    supportsAudio: true,
    supportsNegativePrompt: false,
    supportsSeed: true,
    supportsWatermark: true,
    supportsPromptExtend: false,
    supportsMediaOnly: true,
    notes: 'Seedance 1.x 仅支持文生和图生；1.5 Pro 支持有声与智能时长，1.0 Pro Fast 不支持尾帧。2.0 / Fast / Mini 与 2.5 支持全模态参考和有声生成；只有 2.0 标准版支持 4K，2.5 的优势是最长 30 秒与更高参考素材上限。',
    docsUrl: 'https://docs.volcengine.com/docs/82379/1520757',
  },
  {
    id: 'rolldek',
    name: 'RollDek',
    vendor: 'RollDek',
    enabled: true,
    models: rollDekModels,
    modes: ['text', 'frames', 'reference'],
    media: ['first_frame', 'last_frame', 'reference_image', 'reference_video', 'reference_audio'],
    mediaLimits: {
      first_frame: frameLimits,
      last_frame: frameLimits,
      reference_image: { ...imageReferenceLimit, max: 10 },
      reference_video: { ...videoReferenceLimit, max: 5, requiresDuration: true },
      reference_audio: { ...audioReferenceLimit, max: 5 },
    },
    mediaCombinationLimits: [{
      types: ['first_frame', 'last_frame', 'reference_image'],
      max: 10,
      message: 'RollDek reference_images 合计最多 10 张（包含首帧、尾帧和参考图）',
    }],
    resolutions: rollDekResolutions,
    ratios: ['adaptive', '16:9', '9:16', '1:1'],
    duration: { min: 2, max: 30, smart: false, videoAware: false },
    supportsAudio: false,
    supportsNegativePrompt: false,
    supportsSeed: false,
    supportsWatermark: false,
    supportsPromptExtend: false,
    supportsMediaOnly: false,
    requiresHttpsMediaUrls: true,
    notes: 'RollDek 通过统一 WAN 3.0 视频接口异步生成；模型后缀决定 480P/720P/1080P。标准版与 Prime 支持图片、视频、音频参考，Image 系列不支持参考视频；参考视频时长会计入标准版/Prime 的计费秒数。',
    docsUrl: 'https://rolldek.com',
  },
  {
    id: 'runway',
    name: 'Runway Dev',
    vendor: 'Runway AI',
    enabled: false,
    models: runwayModels,
    modes: ['text', 'frames', 'reference'],
    media: runwayMultimodalMedia,
    mediaLimits: {
      first_frame: runwayFrameLimit,
      last_frame: runwayFrameLimit,
      reference_image: { ...runwayImageLimit, max: 30 },
      reference_video: { ...runwayVideoLimit, max: 9 },
      reference_audio: { ...runwayAudioLimit, max: 10 },
    },
    resolutions: ['480P', '768P', '720P', '1080P', '2K', '4K'],
    ratios: ['adaptive', '21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
    duration: { min: 2, max: 30, smart: true, videoAware: false },
    supportsAudio: true,
    supportsNegativePrompt: false,
    supportsSeed: true,
    supportsWatermark: false,
    supportsPromptExtend: false,
    supportsMediaOnly: false,
    requiresHttpsMediaUrls: true,
    notes: '当前接入 Gen-4.5 与多模态视频模型；适配器按输入素材选择 text_to_video、image_to_video 或 video_to_video，任务输出 URL 为临时地址并沿用统一归档流程。',
    docsUrl: 'https://docs.dev.runwayml.com/api/',
  },
]

const capabilityById = new Map(providerCapabilities.map(item => [item.id, item]))

export function getCapability(id: string) {
  return capabilityById.get(id)
}
